### PR TITLE
fix: empty 1st row in Days Calendar

### LINKED ISSUE #378: Empty row Showing in Calendar Days View for October 2023
In CalendarPicker if firstDay(prop) is 0 and firstDay of Month lies on Sunday then instead of 5 rows 6 rows are rendered where 1st row is empty(or contains last month dates if showDayStragglers is true).

For reproducible example, Please refer: [Expo Snack](https://snack.expo.dev/@jadonshubham/calendarpickeremptyrow). (Go to October 2023 in Calendar)

Here is the screenshot of October 2023
image

### PR DESCRIPTION
**Pull request by shubhamjadon**
Fixes #378 

This issue was happening when firstWeekDay of month is 7 and firstDay prop value is 0 which make startIndex 7 but as per logic startIndex should be from 0 to 6, so this leads render of an empty row as first row.

Fix: Correct value of startIndex for this case should be 0. Hence added % 7 to restrict startIndex to be from 0 to  6.

### CODE REVIEW

**Review by tranjog — APPROVED** [review]
@peacechen This looks good to me, can you have a look and merge if you're happy?

File: CalendarPicker/DaysGridView.js [hunk 1]
```diff
@@ -45,7 +45,7 @@ export default class DaysGridView extends Component {
       const firstWeekDay = getISODay(firstDayOfMonth);
 
       // Determine starting index based on first day of week prop.
-      const startIndex = (firstDay > 0) ? (firstWeekDay + Utils.FIRST_DAY_OFFSETS[firstDay]) % 7 : firstWeekDay;
+      const startIndex = (firstDay > 0) ? (firstWeekDay + Utils.FIRST_DAY_OFFSETS[firstDay]) % 7 : firstWeekDay % 7;
```
Comment (peacechen) [inline CalendarPicker/DaysGridView.js:48]: It would be clearer to move the mod outside the ternary since it applies to both cases.
```
const startIndex = ((firstDay > 0) ? (firstWeekDay + Utils.FIRST_DAY_OFFSETS[firstDay]) : firstWeekDay) % 7;
```

**Comment by peacechen** [comment]
Thanks @shubhamjadon for contributing. Apologies for the delay, I missed this notification in my inbox. I added a suggestion in the code.

File: CalendarPicker/DaysGridView.js (hunk 1 above)
Comment (shubhamjadon) [reply CalendarPicker/DaysGridView.js]: @peacechen Please review, I have updated code as per suggestion.

Comment (peacechen) [reply CalendarPicker/DaysGridView.js]: Thanks @shubhamjadon
